{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      role: redis
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        role: redis
    spec:
      containers:
      - name: twentycrm-redis
        image: {{ .Values.redis.image }}
        imagePullPolicy: Always
        command:
          - redis-server
          - --maxmemory-policy
          - noeviction
        ports:
        - containerPort: 6379
          name: tcp
          protocol: TCP
        resources:
          {{- toYaml .Values.redis.resources | indent 12 | printf "\n%s" }}
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
{{- end }}
