{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
   nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";
   {{- if .Values.ingress.ssl.enabled }}
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   cert-manager.io/cluster-issuer: {{ .Values.ingress.ssl.clusterIssuer | quote }}
   {{- else }}
   nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
   {{- end }}
   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
   {{- range $key, $value := .Values.ingress.annotations }}
   {{ $key }}: {{ $value | quote }}
   {{- end }}

spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-server
            port:
              name: http-tcp

  {{- if .Values.ingress.ssl.enabled }}
  tls:
  - secretName: {{ .Values.ingress.ssl.secretName | default (printf "%s-tls" .Values.ingress.host) }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- if .Values.ingress.ssl.hosts }}
    {{- range .Values.ingress.ssl.hosts }}
    - {{ . }}
    {{- end }}
    {{- end }}
  {{- end -}}
{{- end }}
