apiVersion: v2
description: A Helm chart for Twenty CRM - https://github.com/twentyhq/twenty
name: twentycrm
version: 0.5.0
appVersion: latest
keywords:
  - crm
  - twenty
  - customer-relationship-management
home: https://twenty.com
sources:
  - https://github.com/twentyhq/twenty
maintainers:
  - name: matthieupetite
    url: https://github.com/matthieupetite
